spring:
  servlet:
    context-parameters:
      contextClass: org.springframework.web.context.support.AnnotationConfigWebApplicationContext
      contextConfigLocation: com.test.task_10.AppConfig

  datasource:
    url: jdbc:postgresql://localhost:5432/senla_financial_manager
    username: postgres
    password: 1111

  jpa:
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false