spring:
  servlet:
    driver-class-name: org.h2.Driver
    context-parameters:
      contextClass: org.springframework.web.context.support.AnnotationConfigWebApplicationContext
      contextConfigLocation: com.test.task_10.AppConfig

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8082
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false